/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Products */
        get: operations["get_products_products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/provider/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Provider Products */
        get: operations["get_provider_products_provider_products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/provider/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Provider Product */
        put: operations["put_provider_product_provider_products__product_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Admin Products */
        get: operations["get_admin_products_admin_products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Admin Product */
        put: operations["put_admin_product_admin_products__product_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Order Preview */
        post: operations["post_order_preview_orders_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Order */
        post: operations["post_order_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Order Detail */
        get: operations["get_order_detail_orders__order_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patient/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Patient Orders */
        get: operations["get_patient_orders_patient_orders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{order_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Cancel Order */
        post: operations["post_cancel_order_orders__order_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{order_id}/pay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Pay Order */
        post: operations["post_pay_order_orders__order_id__pay_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/provider/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Provider Dashboard */
        get: operations["get_provider_dashboard_provider_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{order_id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Order Audit */
        get: operations["get_order_audit_orders__order_id__audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminProductResponse */
        AdminProductResponse: {
            /** Id */
            id: number;
            /** Sku */
            sku: string;
            /** Name */
            name: string;
            /** Unit Cogs Cents */
            unit_cogs_cents: number;
            /** Suggested Price Cents */
            suggested_price_cents: number;
            /** Stock Qty */
            stock_qty: number;
            /** Default Dosing */
            default_dosing: string;
        };
        /** AdminProductUpdate */
        AdminProductUpdate: {
            /** Stock Qty */
            stock_qty?: number | null;
            /** Unit Cogs Cents */
            unit_cogs_cents?: number | null;
            /** Default Dosing */
            default_dosing?: string | null;
        };
        /** AuditLedgerResponse */
        AuditLedgerResponse: {
            /** Entry Type */
            entry_type: string;
            /** Amount Cents */
            amount_cents: number;
            /** Created At */
            created_at: string;
        };
        /** AuditLineResponse */
        AuditLineResponse: {
            /** Product Id */
            product_id: number;
            /** Product Name */
            product_name: string;
            /** Qty */
            qty: number;
            /** Unit Price Cents */
            unit_price_cents: number;
            /** Unit Cogs Cents */
            unit_cogs_cents: number;
            /** Line Total Cents */
            line_total_cents: number;
            /** Line Cogs Cents */
            line_cogs_cents: number;
            /** Line Margin Cents */
            line_margin_cents: number;
        };
        /** AuditResponse */
        AuditResponse: {
            /** Id */
            id: number;
            /** Status */
            status: string;
            /** Payment Ref */
            payment_ref: string | null;
            /** Paid At */
            paid_at: string | null;
            /** Lines */
            lines: components["schemas"]["AuditLineResponse"][];
            /** Subtotal Cents */
            subtotal_cents: number;
            /** Cogs Total Cents */
            cogs_total_cents: number;
            /** Fee Bps */
            fee_bps: number;
            /** Platform Fee Cents */
            platform_fee_cents: number;
            /** Provider Payout Cents */
            provider_payout_cents: number;
            /** Ledger */
            ledger: components["schemas"]["AuditLedgerResponse"][];
            /** Recomputed Fee Matches */
            recomputed_fee_matches: boolean;
            /** Split Adds Up */
            split_adds_up: boolean;
            /** Ledger Matches Split */
            ledger_matches_split: boolean;
        };
        /** CatalogProductResponse */
        CatalogProductResponse: {
            /** Id */
            id: number;
            /** Sku */
            sku: string;
            /** Name */
            name: string;
            /** Unit Cogs Cents */
            unit_cogs_cents: number;
            /** Suggested Price Cents */
            suggested_price_cents: number;
            /** Stock Qty */
            stock_qty: number;
            /** Default Dosing */
            default_dosing: string;
        };
        /** CreateLineRequest */
        CreateLineRequest: {
            /** Product Id */
            product_id: number;
            /** Qty */
            qty: number;
            /** Unit Price Cents */
            unit_price_cents: number;
            /** Dosing */
            dosing: string;
            /** Note */
            note?: string | null;
        };
        /** CreateOrderRequest */
        CreateOrderRequest: {
            /** Patient Id */
            patient_id: number;
            /** Lines */
            lines: components["schemas"]["CreateLineRequest"][];
        };
        /** DashboardResponse */
        DashboardResponse: {
            /** Gmv Cents */
            gmv_cents: number;
            /** Platform Fee Cents */
            platform_fee_cents: number;
            /** Earnings Cents */
            earnings_cents: number;
            /** Paid Orders */
            paid_orders: components["schemas"]["PaidOrderResponse"][];
            /** Units Sold */
            units_sold: components["schemas"]["UnitSoldResponse"][];
            /** Pending Orders */
            pending_orders: components["schemas"]["PendingOrderResponse"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** OrderLineResponse */
        OrderLineResponse: {
            /** Product Id */
            product_id: number;
            /** Product Name */
            product_name: string;
            /** Qty */
            qty: number;
            /** Unit Price Cents */
            unit_price_cents: number;
            /** Unit Cogs Cents */
            unit_cogs_cents: number;
            /** Line Total Cents */
            line_total_cents: number;
            /** Line Cogs Cents */
            line_cogs_cents: number;
            /** Line Margin Cents */
            line_margin_cents: number;
            /** Dosing */
            dosing: string;
            /** Note */
            note: string | null;
        };
        /** OrderResponse */
        OrderResponse: {
            /** Id */
            id: number;
            /** Provider Id */
            provider_id: number;
            /** Patient Id */
            patient_id: number;
            /** Status */
            status: string;
            /** Patient Link */
            patient_link: string;
            /** Created At */
            created_at: string;
            /** Paid At */
            paid_at: string | null;
            /** Cancelled At */
            cancelled_at: string | null;
            /** Payment Ref */
            payment_ref: string | null;
            /** Lines */
            lines: components["schemas"]["OrderLineResponse"][];
            /** Subtotal Cents */
            subtotal_cents: number;
            /** Cogs Total Cents */
            cogs_total_cents: number;
            /** Fee Bps */
            fee_bps: number;
            /** Platform Fee Cents */
            platform_fee_cents: number;
            /** Provider Payout Cents */
            provider_payout_cents: number;
        };
        /** PaidOrderResponse */
        PaidOrderResponse: {
            /** Id */
            id: number;
            /** Paid At */
            paid_at: string;
            /** Patient Id */
            patient_id: number;
            /** Patient Name */
            patient_name: string;
            /** Subtotal Cents */
            subtotal_cents: number;
            /** Platform Fee Cents */
            platform_fee_cents: number;
            /** Provider Payout Cents */
            provider_payout_cents: number;
            /** Audit Link */
            audit_link: string;
        };
        /** PayRequest */
        PayRequest: {
            /**
             * Payment Method
             * @enum {string}
             */
            payment_method: "fake_card_ok" | "fake_card_decline";
        };
        /** PendingOrderResponse */
        PendingOrderResponse: {
            /** Id */
            id: number;
            /** Created At */
            created_at: string;
            /** Patient Id */
            patient_id: number;
            /** Patient Name */
            patient_name: string;
        };
        /** PreviewLineRequest */
        PreviewLineRequest: {
            /** Product Id */
            product_id: number;
            /** Qty */
            qty: number;
            /** Unit Price Cents */
            unit_price_cents: number;
        };
        /** PreviewLineResponse */
        PreviewLineResponse: {
            /** Product Id */
            product_id: number;
            /** Qty */
            qty: number;
            /** Unit Price Cents */
            unit_price_cents: number;
            /** Unit Cogs Cents */
            unit_cogs_cents: number;
            /** Line Total Cents */
            line_total_cents: number;
            /** Line Cogs Cents */
            line_cogs_cents: number;
            /** Line Margin Cents */
            line_margin_cents: number;
            /** Stock Available */
            stock_available: number;
        };
        /** PreviewRequest */
        PreviewRequest: {
            /** Lines */
            lines: components["schemas"]["PreviewLineRequest"][];
        };
        /** PreviewResponse */
        PreviewResponse: {
            /** Lines */
            lines: components["schemas"]["PreviewLineResponse"][];
            /** Subtotal Cents */
            subtotal_cents: number;
            /** Cogs Total Cents */
            cogs_total_cents: number;
            /** Fee Bps */
            fee_bps: number;
            /** Platform Fee Cents */
            platform_fee_cents: number;
            /** Provider Payout Cents */
            provider_payout_cents: number;
        };
        /** ProviderProductResponse */
        ProviderProductResponse: {
            /** Product Id */
            product_id: number;
            /** Sku */
            sku: string;
            /** Name */
            name: string;
            /** Enabled */
            enabled: boolean;
            /** Default Price Cents */
            default_price_cents: number;
            /** Unit Cogs Cents */
            unit_cogs_cents: number;
            /** Stock Qty */
            stock_qty: number;
            /** Default Dosing */
            default_dosing: string;
        };
        /** ProviderProductUpdate */
        ProviderProductUpdate: {
            /** Enabled */
            enabled: boolean;
            /** Default Price Cents */
            default_price_cents: number;
        };
        /** UnitSoldResponse */
        UnitSoldResponse: {
            /** Product Id */
            product_id: number;
            /** Product Name */
            product_name: string;
            /** Qty */
            qty: number;
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Role */
            role: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_users_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"][];
                };
            };
        };
    };
    me_me_get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_products_products_get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogProductResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_provider_products_provider_products_get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderProductResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_provider_product_provider_products__product_id__put: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderProductUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderProductResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_admin_products_admin_products_get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminProductResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_admin_product_admin_products__product_id__put: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminProductUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminProductResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_order_preview_orders_preview_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_order_orders_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_order_detail_orders__order_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_patient_orders_patient_orders_get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_cancel_order_orders__order_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_pay_order_orders__order_id__pay_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PayRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_provider_dashboard_provider_dashboard_get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_order_audit_orders__order_id__audit_get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
